export const AUTH_USER_REPOSITORY = Symbol('AUTH_USER_REPOSITORY');
export const USER_SESSION_REPOSITORY = Symbol('USER_SESSION_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const PASSWORD_RESET_TOKEN_REPOSITORY = Symbol('PASSWORD_RESET_TOKEN_REPOSITORY');
export const AUTH_EVENT_REPOSITORY = Symbol('AUTH_EVENT_REPOSITORY');
