export enum ActorType {
  CLIENT = 'CLIENT',
  SALES_REPRESENTATIVE = 'SALES_REPRESENTATIVE',
  ENGINEER_TECHNICIAN = 'ENGINEER_TECHNICIAN',
  COMMERCIAL_ADMINISTRATOR = 'COMMERCIAL_ADMINISTRATOR',
  EXTERNAL_SUBCONTRACTOR = 'EXTERNAL_SUBCONTRACTOR',
  ACCOUNTING_FINANCE = 'ACCOUNTING_FINANCE',
  MANAGEMENT = 'MANAGEMENT',
}
