name: Local
variables:
  - name: baseUrl
    value: http://localhost:80/api
    enabled: true
    secret: false
    type: text
  - name: companyId
    value: ""
    enabled: true
    secret: false
    type: text
  - name: companyTaxId
    value: 12-3456789
    enabled: true
    secret: false
    type: text
  - name: systemOwnerEmail
    value: admin@obralink.local
    enabled: true
    secret: false
    type: text
  - name: systemOwnerPassword
    value: Admin123!
    enabled: true
    secret: true
    type: text
  - name: trackingId
    value: 8b7a5a64-7df4-4f6d-a690-a8d0c1e89c7a
    enabled: true
    secret: false
    type: text
  - name: userId
    value: ""
    enabled: true
    secret: false
    type: text
  - name: roleId
    value: ""
    enabled: true
    secret: false
    type: text
