export const TENANT_REPOSITORY = Symbol('TENANT_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const ACTOR_REPOSITORY = Symbol('ACTOR_REPOSITORY');
